// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEPvnARNRCrAC3s-_NiBh2HKiLtneJKbQ',
    appId: '1:1083303777359:web:e7a5e20b09147ad952463a',
    messagingSenderId: '1083303777359',
    projectId: 'bossbaby-8263b',
    authDomain: 'bossbaby-8263b.firebaseapp.com',
    storageBucket: 'bossbaby-8263b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5JckFUhzpcYbm8uDpDeqonkZxIvM5lVs',
    appId: '1:1083303777359:android:71ae90f02fd07e0d52463a',
    messagingSenderId: '1083303777359',
    projectId: 'bossbaby-8263b',
    storageBucket: 'bossbaby-8263b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0Rj7QK8zgi5aztR0FSlYUdbG0ZX5i5wY',
    appId: '1:1083303777359:ios:2fa47235b0f73d3752463a',
    messagingSenderId: '1083303777359',
    projectId: 'bossbaby-8263b',
    storageBucket: 'bossbaby-8263b.appspot.com',
    iosBundleId: 'com.example.scopeindiaStudent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0Rj7QK8zgi5aztR0FSlYUdbG0ZX5i5wY',
    appId: '1:1083303777359:ios:2fa47235b0f73d3752463a',
    messagingSenderId: '1083303777359',
    projectId: 'bossbaby-8263b',
    storageBucket: 'bossbaby-8263b.appspot.com',
    iosBundleId: 'com.example.scopeindiaStudent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEPvnARNRCrAC3s-_NiBh2HKiLtneJKbQ',
    appId: '1:1083303777359:web:142f37ca1f5e80e552463a',
    messagingSenderId: '1083303777359',
    projectId: 'bossbaby-8263b',
    authDomain: 'bossbaby-8263b.firebaseapp.com',
    storageBucket: 'bossbaby-8263b.appspot.com',
  );
}
